import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowDownToLine, ArrowUpRight, CheckCircle2, ExternalLink, Loader2, RefreshCw, ShieldCheck, Zap } from 'lucide-react';
import { createViemAdapterFromProvider } from '@circle-fin/adapter-viem-v2';
import { UnifiedBalanceKit } from '@circle-fin/unified-balance-kit';
import type { EIP1193Provider } from 'viem';
import { isAddress } from 'viem';
import { useAccount, useChainId, useSwitchChain } from 'wagmi';
import { ARC_CHAIN_ID, ARC_MAINNET_EXPLORER_URL } from '../../config/arc';
import { useWallet } from '../../context/WalletContext';
const ARC_GATEWAY_CHAIN = 'Arc';
const DESTINATIONS = [{ id: 'Base', label: 'Base' }, { id: 'Ethereum', label: 'Ethereum' }, { id: 'Arbitrum', label: 'Arbitrum' }, { id: 'Optimism', label: 'Optimism' }, { id: 'Polygon', label: 'Polygon' }, { id: 'Avalanche', label: 'Avalanche' }, { id: 'Arc', label: 'Arc' }];
const kit = new UnifiedBalanceKit();
function cleanError(error: unknown) { const message = error instanceof Error ? error.message : String(error || 'Gateway request failed.'); if (/user rejected|user denied|rejected the request|4001/i.test(message)) return 'Rejected'; return message.replace(/^Error:\s*/i, '') || 'Gateway request failed.'; }
function explorerFor(chain: string, hash?: string | null) { if (!hash) return null; if (chain === 'Arc') return \`${ARC_MAINNET_EXPLORER_URL}/tx/${hash}\`; return null; }
export const GatewayView: React.FC = () => {
  const { address } = useWallet(); const { connector } = useAccount(); const chainId = useChainId(); const { switchChainAsync } = useSwitchChain();
  const [balance, setBalance] = useState('0.000000'); const [breakdown, setBreakdown] = useState<Array<{ chain: string; balance: string }>>([]);
  const [depositAmount, setDepositAmount] = useState(''); const [spendAmount, setSpendAmount] = useState(''); const [destination, setDestination] = useState('Base'); const [recipient, setRecipient] = useState(address || '');
  const [loading, setLoading] = useState(false); const [busy, setBusy] = useState<'deposit' | 'spend' | null>(null); const [status, setStatus] = useState<string | null>(null); const [txHash, setTxHash] = useState<string | null>(null); const [explorerUrl, setExplorerUrl] = useState<string | null>(null);
  useEffect(() => { if (address && (!recipient || !isAddress(recipient))) setRecipient(address); }, [address, recipient]);
  const getAdapter = useCallback(async () => { if (!connector) throw new Error('Connect a wallet first.'); if (chainId !== ARC_CHAIN_ID) await switchChainAsync({ chainId: ARC_CHAIN_ID }); const provider = (await connector.getProvider()) as EIP1193Provider; return await createViemAdapterFromProvider({ provider }); }, [connector, chainId, switchChainAsync]);
  const refresh = useCallback(async () => { if (!connector) return; setLoading(true); try { const adapter = await getAdapter(); const result: any = await kit.getBalances({ sources: { adapter } }); setBalance(result?.totalConfirmedBalance || '0.000000'); const rows = result?.breakdown?.flatMap((depositor: any) => depositor?.breakdown || []) || []; setBreakdown(rows.filter((row: any) => Number(row?.confirmedBalance || 0) > 0).map((row: any) => ({ chain: row.chain, balance: row.confirmedBalance }))); } catch (error) { setStatus(cleanError(error)); } finally { setLoading(false); } }, [connector, getAdapter]);
  useEffect(() => { refresh(); }, [refresh, address]);
  const deposit = async () => { setStatus(null); setTxHash(null); setExplorerUrl(null); const amount = Number(depositAmount); if (!Number.isFinite(amount) || amount <= 0) return setStatus('Enter a deposit amount greater than zero.'); setBusy('deposit'); try { const adapter = await getAdapter(); const result: any = await kit.deposit({ from: { adapter, chain: ARC_GATEWAY_CHAIN }, amount: amount.toFixed(6) }); setTxHash(result?.txHash || null); setExplorerUrl(result?.explorerUrl || explorerFor('Arc', result?.txHash)); setStatus('Gateway deposit confirmed.'); setDepositAmount(''); await refresh(); } catch (error) { setStatus(cleanError(error)); } finally { setBusy(null); } };
  const spend = async () => { setStatus(null); setTxHash(null); setExplorerUrl(null); const amount = Number(spendAmount); if (!Number.isFinite(amount) || amount <= 0) return setStatus('Enter an amount greater than zero.'); if (!isAddress(recipient)) return setStatus('Enter a valid recipient address.'); if (amount > Number(balance)) return setStatus('Insufficient Gateway balance.'); setBusy('spend'); try { const adapter = await getAdapter(); const result: any = await kit.spend({ from: { adapter, allocations: { amount: amount.toFixed(6), chain: ARC_GATEWAY_CHAIN } }, to: { chain: destination, recipientAddress: recipient, useForwarder: true }, amount: amount.toFixed(6) }); setTxHash(result?.txHash || null); setExplorerUrl(result?.explorerUrl || explorerFor(destination, result?.txHash)); setStatus('Gateway transfer confirmed.'); setSpendAmount(''); await refresh(); } catch (error) { setStatus(cleanError(error)); } finally { setBusy(null); } };
  const destinationLabel = useMemo(() => DESTINATIONS.find((item) => item.id === destination)?.label || destination, [destination]);
  return <div className="min-h-[calc(100vh-3.5rem)] p-5 sm:p-8 lg:p-10"><div className="max-w-5xl mx-auto space-y-6">
    <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[0.25em] text-violet-400 font-mono">Circle Gateway</p><h1 className="mt-1 text-2xl sm:text-3xl font-bold text-white tracking-tight">Unified USDC</h1><p className="mt-2 text-sm text-zinc-400">Deposit USDC once, then access your unified balance across supported chains.</p></div><button onClick={refresh} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-zinc-800 px-3.5 py-2.5 text-xs font-semibold text-zinc-300 hover:text-white disabled:opacity-50"><RefreshCw className={loading ? 'w-3.5 h-3.5 animate-spin' : 'w-3.5 h-3.5'} /> Refresh</button></div>
    <div className="rounded-2xl border border-violet-400/20 bg-[#0d0f12] p-5 sm:p-7"><div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-5"><div><div className="text-[10px] uppercase tracking-widest text-zinc-600 font-mono">Gateway unified balance</div><div className="mt-2 text-3xl sm:text-4xl font-bold text-white font-mono">{Number(balance).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 6 })} <span className="text-base text-violet-300">USDC</span></div><div className="mt-2 flex items-center gap-2 text-[11px] text-zinc-500"><ShieldCheck className="w-3.5 h-3.5 text-lime-300" /> Circle Gateway • Mainnet</div></div><div className="rounded-xl border border-violet-400/10 bg-violet-400/[0.03] px-4 py-3 text-xs text-zinc-400 max-w-sm">Gateway is permissionless and uses Circle's unified USDC balance model across supported chains.</div></div>{breakdown.length > 0 && <div className="mt-6 grid grid-cols-2 sm:grid-cols-4 gap-2.5">{breakdown.map((row) => <div key={row.chain} className="rounded-xl border border-zinc-800 bg-zinc-950 p-3"><div className="text-[10px] text-zinc-600">{row.chain}</div><div className="mt-1 text-sm font-mono text-zinc-200">{Number(row.balance).toLocaleString(undefined, { maximumFractionDigits: 6 })}</div></div>)}</div>}</div>
    <div className="grid lg:grid-cols-2 gap-4"><div className="rounded-2xl border border-violet-400/15 bg-[#0d0f12] p-5 sm:p-6 space-y-4"><div className="flex items-center gap-2"><ArrowDownToLine className="w-4 h-4 text-violet-300" /><div><div className="text-sm font-semibold text-white">Deposit from Arc</div><div className="text-[11px] text-zinc-500 mt-0.5">Move Arc Mainnet USDC into your unified Gateway balance.</div></div></div><label className="block"><span className="text-[11px] text-zinc-500">Amount</span><div className="mt-2 flex items-center rounded-xl border border-zinc-800 bg-zinc-950 px-3.5"><input value={depositAmount} onChange={(e) => setDepositAmount(e.target.value.replace(/[^0-9.]/g, ''))} placeholder="0.00" inputMode="decimal" className="w-full bg-transparent py-3 text-lg font-mono text-white outline-none" /><span className="text-xs font-semibold text-zinc-500">USDC</span></div></label><button onClick={deposit} disabled={busy !== null} className="w-full flex items-center justify-center gap-2 rounded-xl bg-white py-3 text-xs font-bold text-black hover:bg-zinc-200 disabled:opacity-50">{busy === 'deposit' ? <Loader2 className="w-4 h-4 animate-spin" /> : <ArrowDownToLine className="w-4 h-4" />}{busy === 'deposit' ? 'Depositing...' : 'Deposit to Gateway'}</button></div>
    <div className="rounded-2xl border border-blue-400/15 bg-[#0d0f12] p-5 sm:p-6 space-y-4"><div className="flex items-center gap-2"><ArrowUpRight className="w-4 h-4 text-blue-300" /><div><div className="text-sm font-semibold text-white">Send from Gateway</div><div className="text-[11px] text-zinc-500 mt-0.5">Use your unified USDC balance without pre-positioning funds.</div></div></div><div className="grid sm:grid-cols-2 gap-3"><label className="block"><span className="text-[11px] text-zinc-500">Destination</span><select value={destination} onChange={(e) => setDestination(e.target.value)} className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-950 px-3.5 py-3 text-sm text-white outline-none">{DESTINATIONS.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label className="block"><span className="text-[11px] text-zinc-500">Amount</span><div className="mt-2 flex items-center rounded-xl border border-zinc-800 bg-zinc-950 px-3.5"><input value={spendAmount} onChange={(e) => setSpendAmount(e.target.value.replace(/[^0-9.]/g, ''))} placeholder="0.00" inputMode="decimal" className="w-full bg-transparent py-3 text-lg font-mono text-white outline-none" /><span className="text-xs font-semibold text-zinc-500">USDC</span></div></label></div><label className="block"><span className="text-[11px] text-zinc-500">Recipient</span><input value={recipient} onChange={(e) => setRecipient(e.target.value)} placeholder="0x..." className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-950 px-3.5 py-3 text-sm font-mono text-white outline-none focus:border-blue-500/40" /></label><button onClick={spend} disabled={busy !== null} className="w-full flex items-center justify-center gap-2 rounded-xl bg-blue-500 py-3 text-xs font-bold text-white hover:bg-blue-400 disabled:opacity-50">{busy === 'spend' ? <Loader2 className="w-4 h-4 animate-spin" /> : <Zap className="w-4 h-4" />}{busy === 'spend' ? 'Sending...' : \`Send \${destinationLabel}\`}</button></div></div>
    {status && <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 px-4 py-3 text-xs text-zinc-300">{status}</div>}{txHash && <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-lime-400/15 bg-lime-400/[0.03] px-4 py-3"><div className="flex items-center gap-2 text-xs text-lime-200"><CheckCircle2 className="w-4 h-4" /> Confirmed transaction</div>{explorerUrl && <a href={explorerUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-[11px] text-blue-400"><ExternalLink className="w-3 h-3" /> View on explorer</a>}</div>}
    <div className="rounded-xl border border-zinc-800 bg-zinc-900/30 px-4 py-3 text-[11px] text-zinc-600">Circle Gateway is USDC-only. GEN-0FI does not execute anything automatically; every deposit or transfer requires your wallet confirmation.</div>
  </div></div>;
};