import React, { useEffect, useMemo, useState } from 'react';
import { AddressBook as AddressBookIcon, Check, Copy, Pencil, Plus, Search, Send, Trash2, X } from 'lucide-react';
import { isAddress } from 'viem';
import { useWallet } from '../../context/WalletContext';
type Contact = { id: string; name: string; address: string; note?: string };
const STORAGE_PREFIX = 'gen0fi-address-book:';
const storageKey = (address: string) => STORAGE_PREFIX + address.toLowerCase();
export interface AddressBookViewProps { onSendTo?: (address: string) => void; }
export const AddressBookView: React.FC<AddressBookViewProps> = ({ onSendTo }) => {
  const { address } = useWallet();
  const [contacts, setContacts] = useState<Contact[]>([]);
  const [query, setQuery] = useState(''); const [editing, setEditing] = useState<Contact | null>(null); const [isAdding, setIsAdding] = useState(false);
  const [name, setName] = useState(''); const [walletAddress, setWalletAddress] = useState(''); const [note, setNote] = useState('');
  const [copied, setCopied] = useState<string | null>(null); const [error, setError] = useState('');
  useEffect(() => { if (!address) { setContacts([]); return; } try { const raw = localStorage.getItem(storageKey(address)); const parsed = raw ? JSON.parse(raw) : []; setContacts(Array.isArray(parsed) ? parsed : []); } catch { setContacts([]); } }, [address]);
  const persist = (next: Contact[]) => { setContacts(next); if (address) localStorage.setItem(storageKey(address), JSON.stringify(next)); };
  const resetForm = () => { setName(''); setWalletAddress(''); setNote(''); setEditing(null); setIsAdding(false); setError(''); };
  const openAdd = () => { resetForm(); setIsAdding(true); };
  const openEdit = (c: Contact) => { setEditing(c); setIsAdding(false); setName(c.name); setWalletAddress(c.address); setNote(c.note || ''); setError(''); };
  const save = () => {
    setError(''); const cleanName = name.trim(); const cleanAddress = walletAddress.trim();
    if (!cleanName) return setError('Enter a name for this address.'); if (!isAddress(cleanAddress)) return setError('Enter a valid EVM wallet address.');
    if (contacts.some((c) => c.address.toLowerCase() === cleanAddress.toLowerCase() && c.id !== editing?.id)) return setError('That address is already in your address book.');
    const next: Contact[] = editing ? contacts.map((c) => c.id === editing.id ? { ...c, name: cleanName, address: cleanAddress, note: note.trim() } : c) : [...contacts, { id: crypto.randomUUID(), name: cleanName, address: cleanAddress, note: note.trim() }];
    persist(next.sort((a, b) => a.name.localeCompare(b.name))); resetForm();
  };
  const remove = (id: string) => { if (window.confirm('Remove this address from your address book?')) persist(contacts.filter((c) => c.id !== id)); };
  const copy = async (value: string) => { await navigator.clipboard.writeText(value); setCopied(value); window.setTimeout(() => setCopied(null), 1200); };
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return q ? contacts.filter((c) => `${c.name} ${c.address} ${c.note || ''}`.toLowerCase().includes(q)) : contacts; }, [contacts, query]);
  return <div className="min-h-[calc(100vh-3.5rem)] p-5 sm:p-8 lg:p-10"><div className="max-w-4xl mx-auto space-y-6">
    <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[0.25em] text-cyan-400 font-mono">Wallet utility</p><h1 className="mt-1 text-2xl sm:text-3xl font-bold text-white tracking-tight">Address Book</h1><p className="mt-2 text-sm text-zinc-400">Save trusted Arc-compatible addresses so sending takes less time.</p></div><button onClick={openAdd} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-4 py-2.5 text-xs font-bold text-black hover:bg-zinc-200"><Plus className="w-4 h-4" /> Add address</button></div>
    <div className="flex items-center gap-2 rounded-xl border border-zinc-800 bg-[#0d0f12] px-3.5"><Search className="w-4 h-4 text-zinc-600" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search name or address..." className="w-full bg-transparent py-3 text-sm text-white outline-none placeholder:text-zinc-600" /></div>
    {(isAdding || editing) && <div className="rounded-2xl border border-cyan-400/20 bg-[#0d0f12] p-5 sm:p-6 space-y-4"><div className="flex items-center justify-between"><div className="text-sm font-semibold text-white">{editing ? 'Edit address' : 'Add address'}</div><button onClick={resetForm} className="p-1.5 text-zinc-500 hover:text-white"><X className="w-4 h-4" /></button></div><div className="grid sm:grid-cols-2 gap-4"><label className="block"><span className="text-[11px] text-zinc-500">Name</span><input value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Treasury" className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-950 px-3.5 py-3 text-sm text-white outline-none" /></label><label className="block"><span className="text-[11px] text-zinc-500">Wallet address</span><input value={walletAddress} onChange={(e) => setWalletAddress(e.target.value)} placeholder="0x..." className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-950 px-3.5 py-3 text-sm font-mono text-white outline-none" /></label></div><label className="block"><span className="text-[11px] text-zinc-500">Note <span className="text-zinc-700">(optional)</span></span><input value={note} onChange={(e) => setNote(e.target.value)} placeholder="Short note" className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-950 px-3.5 py-3 text-sm text-white outline-none" /></label>{error && <div className="rounded-xl border border-red-400/20 bg-red-400/[0.04] px-3.5 py-3 text-xs text-red-300">{error}</div>}<div className="flex justify-end gap-2"><button onClick={resetForm} className="rounded-xl border border-zinc-800 px-4 py-2.5 text-xs font-semibold text-zinc-400">Cancel</button><button onClick={save} className="rounded-xl bg-white px-4 py-2.5 text-xs font-bold text-black">{editing ? 'Save changes' : 'Save address'}</button></div></div>}
    {filtered.length === 0 ? <div className="rounded-2xl border border-zinc-800 bg-[#0d0f12] px-6 py-14 text-center"><AddressBookIcon className="mx-auto w-8 h-8 text-cyan-400/70" /><div className="mt-3 text-sm font-semibold text-white">{contacts.length ? 'No matching addresses' : 'Your address book is empty'}</div><div className="mt-1 text-xs text-zinc-500">{contacts.length ? 'Try another search.' : 'Save an address once and reuse it from GEN-0FI.'}</div>{!contacts.length && <button onClick={openAdd} className="mt-5 rounded-xl border border-cyan-400/20 px-4 py-2.5 text-xs font-semibold text-cyan-300">Add your first address</button>}</div> : <div className="space-y-2.5">{filtered.map((c) => <div key={c.id} className="rounded-2xl border border-zinc-800 bg-[#0d0f12] p-4 sm:p-5"><div className="flex flex-col sm:flex-row sm:items-center gap-4"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><div className="text-sm font-semibold text-white truncate">{c.name}</div>{c.note && <span className="text-[10px] text-zinc-600 truncate">{c.note}</span>}</div><div className="mt-1 flex items-center gap-2 min-w-0"><span className="font-mono text-xs text-zinc-500 truncate">{c.address}</span><button onClick={() => copy(c.address)} className="shrink-0 text-zinc-600 hover:text-white">{copied === c.address ? <Check className="w-3.5 h-3.5 text-lime-300" /> : <Copy className="w-3.5 h-3.5" />}</button></div></div><div className="flex items-center gap-1.5"><button onClick={() => onSendTo?.(c.address)} className="inline-flex items-center gap-1.5 rounded-lg border border-blue-400/20 px-3 py-2 text-[11px] font-semibold text-blue-300"><Send className="w-3.5 h-3.5" /> Send</button><button onClick={() => openEdit(c)} className="rounded-lg border border-zinc-800 p-2 text-zinc-500 hover:text-white"><Pencil className="w-3.5 h-3.5" /></button><button onClick={() => remove(c.id)} className="rounded-lg border border-zinc-800 p-2 text-zinc-500 hover:text-red-300"><Trash2 className="w-3.5 h-3.5" /></button></div></div></div>)}</div>}
    <div className="rounded-xl border border-zinc-800 bg-zinc-900/30 px-4 py-3 text-[11px] text-zinc-600">Address book data is stored locally in this browser and is scoped to the connected wallet.</div>
  </div></div>;
};
